on: [push]
jobs:
  build_and_test:
    environment: testing
    env:
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      DEBUG: ${{secrets.DEBUG}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "welcome to vendor api by dev loki"
      - uses: ikalnytskyi/action-setup-postgres@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip

      - run: pip install -r requirements.txt
      - run: echo "migrations .........."
      - run: python manage.py migrate
      - run: echo " running tests"
      - run: pytest -v
